# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 19:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('upload', models.FileField(default='No file uploaded', null=True, upload_to='assignments/')),
                ('due_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Lecturer', 'Lecturer'), ('Student', 'Student')], default='Lecturer', max_length=100)),
                ('faculty', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('matric_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('courses', models.ManyToManyField(blank=True, null=True, related_name='lecturers', to='ams_api.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateField(auto_now=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('grade', models.CharField(blank=True, default='No grade yet', max_length=100, null=True)),
                ('feedback', models.CharField(blank=True, default='No feedback yet', max_length=255, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ams_api.Assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='ams_api.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
