# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-15 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ams_api', '0003_auto_20180108_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='upload',
            field=models.FileField(default=django.utils.timezone.now, upload_to='assignments/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('LR', 'Lecturer'), ('ST', 'Student')], default='Lecturer', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
